services:
  db:
    image: postgres:16-alpine
    container_name: rima2_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: rima2_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3004:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: rima2_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5177:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: